export const DEFAULT_API_ENDPOINT = 'http://localhost:3000/api/memory/process'
export const DEFAULT_API_BASE = 'http://localhost:3000'
export const MIN_CAPTURE_INTERVAL = 10000
export const ACTIVITY_TIMEOUT = 30000
export const CONTENT_CHANGE_THRESHOLD = 0.1
export const MIN_CONTENT_LENGTH = 50
export const MEMORY_INJECTION_DELAY = 1500
export const MEMORY_INJECTION_MIN_LENGTH = 3

export const MESSAGE_TYPES = {
  CAPTURE_CONTEXT: 'CAPTURE_CONTEXT',
  CAPTURE_CONTEXT_NOW: 'CAPTURE_CONTEXT_NOW',
  SET_ENDPOINT: 'SET_ENDPOINT',
  GET_ENDPOINT: 'GET_ENDPOINT',
  GET_EXTENSION_ENABLED: 'GET_EXTENSION_ENABLED',
  SET_EXTENSION_ENABLED: 'SET_EXTENSION_ENABLED',
  GET_MEMORY_INJECTION_ENABLED: 'GET_MEMORY_INJECTION_ENABLED',
  SET_MEMORY_INJECTION_ENABLED: 'SET_MEMORY_INJECTION_ENABLED',
  GET_BLOCKED_WEBSITES: 'GET_BLOCKED_WEBSITES',
  SET_BLOCKED_WEBSITES: 'SET_BLOCKED_WEBSITES',
  ADD_BLOCKED_WEBSITE: 'ADD_BLOCKED_WEBSITE',
  REMOVE_BLOCKED_WEBSITE: 'REMOVE_BLOCKED_WEBSITE',
  CHECK_WEBSITE_BLOCKED: 'CHECK_WEBSITE_BLOCKED',
  CHECK_API_HEALTH: 'CHECK_API_HEALTH',
  SYNC_AUTH_TOKEN: 'SYNC_AUTH_TOKEN',
  PING: 'PING',
} as const

export const STORAGE_KEYS = {
  API_ENDPOINT: 'apiEndpoint',
  EXTENSION_ENABLED: 'extensionEnabled',
  MEMORY_INJECTION_ENABLED: 'memoryInjectionEnabled',
  BLOCKED_WEBSITES: 'blockedWebsites',
  AUTH_TOKEN: 'auth_token',
} as const
