name: recallos-indexer
description: "Envio HyperIndex for RecallOS Memory Registry on Sepolia"

schema: "./schema.graphql"
output: "./generated"

contracts:
  - name: RecallOSMemoryRegistry
    abi_file_path: "./abis/RecallOSMemoryRegistry.json"
    handler: "./src/EventHandlers.ts"
    events:
      - event: MemoryStored
      - event: MemoryBatchStored
      - event: GasDeposited
      - event: GasDeducted
      - event: GasWithdrawn
      - event: RelayerAuthorized

networks:
  - id: 11155111
    rpc: https://eth-sepolia.public.blastapi.io
    start_block: 9400000
    contracts:
      - name: RecallOSMemoryRegistry
        address: 0x40b55b9634fcf2454c138fa5ed914ac7044f931b
        start_block: 9400000

preload_handlers: true